// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션은 direct 연결 필요 — pooled(DATABASE_URL, 앱 런타임용)로는 세션 기능 제약으로 실패할 수 있음
    // https://neon.com/docs/guides/prisma
    url: process.env["DIRECT_URL"],
  },
});
